### ISSUE TITLE
Bot is broken. HTTP 403 on comments when replying in r/anarchychess

### ISSUE THREAD

**Issue by jclocks** [jclocks/levy-rozbot#14]
ERROR:

Traceback (most recent call last):
  File "/home/ladmin/levy-rozbot/./levyRozbot.py", line 47, in <module>
    comment.reply(reply_text)
  File "/home/ladmin/.local/lib/python3.9/site-packages/praw/models/reddit/mixins/replyable.py", line 39, in reply
    comments = self._reddit.post(API_PATH["comment"], data=data)
  File "/home/ladmin/.local/lib/python3.9/site-packages/praw/reddit.py", line 793, in post
    return self._objectify_request(
  File "/home/ladmin/.local/lib/python3.9/site-packages/praw/reddit.py", line 696, in _objectify_request
    self.request(
  File "/home/ladmin/.local/lib/python3.9/site-packages/praw/reddit.py", line 885, in request
    return self._core.request(
  File "/home/ladmin/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 330, in request
    return self._request_with_retries(
  File "/home/ladmin/.local/lib/python3.9/site-packages/prawcore/sessions.py", line 266, in _request_with_retries
    raise self.STATUS_EXCEPTIONS[response.status_code](response)
prawcore.exceptions.Forbidden: received 403 HTTP response

**Comment by jclocks** [comment]
Note: seems to work fine when subreddit is set to testingground4bots. 403's when it's anarchychess.

**Comment by jclocks** [comment]
Confirmed to be a subreddit ban. Talking with mods. Suspecting the youtube link caused it.

**Comment by jclocks** [comment]
Youtube link likely triggered an automatic ban, but mods have upheld the ban as they don't want any bots except u/PetrosianBot.
As such, this project, as is, is dead, and is out of my control. It's over. It was fun.
I do plan on forking this into a nice bot utility for others to use; while the goal of bringing smiles to some Redditor's faces is now dead, the other goal of learning to make a handy bot was a complete success, and I see no reason to continue wasting my efforts.
I will be reverting any reverts soon, as there was nothing wrong with my code.
